<a href="https://colab.research.google.com/github/pandi000/MachineLearning/blob/main/minggu4bab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Apa itu Algoritma k-Nearest Neighbor?***
Algoritma k-Nearest Neighbor adalah algoritma supervised
learning dimana hasil dari instance yang baru diklasifikasikan berdasarkan mayoritas dari kategori k-tetangga terdekat.

Tujuan dari algoritma ini adalah untuk mengklasifikasikan obyek baru berdasarkan atribut dan sample-sample dari training data.

Algoritma k-Nearest Neighbor menggunakan Neighborhood Classification sebagai nilai prediksi dari nilai instance yang baru.

Contoh penggunaan KNN:
Misalkan Anda memiliki dataset gambar yang telah dilabeli sebagai "kucing" atau "anjing". Anda ingin membuat model machine learning yang dapat memprediksi apakah gambar yang tidak dikenal adalah gambar kucing atau anjing berdasarkan fitur-fitur gambar tersebut. Anda dapat menggunakan algoritma KNN untuk melakukan ini. Anda akan menggunakan dataset pelatihan untuk menghitung jarak antara fitur-fitur gambar yang telah dilabeli dan kemudian menggunakan k tetangga terdekat untuk memprediksi apakah gambar yang tidak dikenal adalah gambar kucing atau anjing.

Contoh penggunaan K-Means:
Misalkan Anda memiliki dataset pelanggan e-commerce yang berisi data belanjaan pelanggan, seperti jumlah uang yang dihabiskan, jumlah item yang dibeli, dan frekuensi belanja. Anda ingin mengelompokkan pelanggan ke dalam beberapa kelompok berdasarkan perilaku belanja mereka sehingga Anda dapat membuat strategi pemasaran yang lebih efektif. Anda dapat menggunakan algoritma K-Means untuk melakukan ini. Anda akan menggunakan dataset pelanggan untuk menghitung jarak antara setiap pelanggan dan pusat kelompok, dan kemudian mengelompokkan pelanggan ke dalam kelompok-kelompok berdasarkan jarak mereka dari pusat kelompok.

In [2]:
#memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku =  load_iris()

In [3]:
# simpan data fitur/kolom (x) dan target (y)
X = iris_ku.data
Y = iris_ku.target

In [4]:
# simpan nama fitur/kolom (X) dan terget (Y)
feature_names = iris_ku.feature_names
target_names = iris_ku.target_names

In [5]:
# tampil nama fitur dan terget dataset
print("Feature names:", feature_names)
print("Target_names:", target_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target_names: ['setosa' 'versicolor' 'virginica']


In [6]:
# X dan Y adalah numpy array
print("\nType of X is:", type(X))


Type of X is: <class 'numpy.ndarray'>


In [7]:
# tampilkan 5 baris pertama
print("nFirst 5 rows of x:", X[:5])

nFirst 5 rows of x: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [8]:
# fitur (X) and target (Y)
X = iris_ku.data
Y = iris_ku.target

In [9]:
# splitting x dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split 
X_latih, X_tes, Y_latih, Y_tes = train_test_split(X, Y, test_size=0.4, random_state=1)

In [10]:
# tampilkan data fitur latih dan uji
print(X_latih.shape)
print(X_tes.shape)

(90, 4)
(60, 4)


In [11]:
# tampilkan data fitur latih dan uji
print(Y_latih.shape)
print(Y_tes.shape)

(90,)
(60,)


In [12]:
# pelatihan pada data latih menggunakan KNN (k=3)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_latih, Y_latih)

KNeighborsClassifier(n_neighbors=3)

In [13]:
# melakukan prediksi pada data uji
Y_prediksi = knn.predict(X_tes)

In [14]:
# perbandingan nilai aktual (Y_tes) dengan nilai prediksi (Y_prediksi)
from sklearn import metrics
print("Akurasi model KNN :", metrics.accuracy_score(Y_tes, Y_prediksi))

Akurasi model KNN : 0.9833333333333333


In [15]:
# prediksi menggunakan data sampel dibuat sendiri
contoh = [[3, 5, 4, 2],[2, 3, 5, 4]]
preds = knn.predict(contoh)
pred_species = [iris_ku.target_names[p] for p in preds]
print("Prediksi :", pred_species)

Prediksi : ['versicolor', 'virginica']


In [16]:
# saving the model
import joblib
joblib.dump(knn, 'iris_knn.pkl')

['iris_knn.pkl']

KNN (K-Nearest Neighbors) dan K-Means adalah dua algoritma machine learning yang populer dan digunakan dalam berbagai aplikasi. Namun, mereka berbeda dalam cara mereka bekerja dan jenis masalah yang dapat mereka selesaikan.

KNN (K-Nearest Neighbors)
KNN adalah algoritma supervised learning, yang berarti bahwa ia menggunakan data yang telah dilabeli untuk membuat prediksi tentang data yang tidak dikenal. KNN bekerja dengan mencari k titik data terdekat dalam dataset pelatihan dan mengambil mayoritas label k tetangga terdekat untuk memprediksi label data yang tidak dikenal.
Contoh penggunaan KNN adalah untuk klasifikasi gambar, di mana kita ingin mengklasifikasikan gambar berdasarkan label yang telah ditentukan. KNN juga dapat digunakan untuk regresi, di mana kita ingin memprediksi nilai numerik berdasarkan nilai-nilai fitur yang diberikan.

K-Means
K-Means adalah algoritma unsupervised learning, yang berarti bahwa ia tidak menggunakan data yang dilabeli. K-Means bekerja dengan mengelompokkan titik data ke dalam k kelompok berdasarkan jaraknya dari pusat kelompok. Jarak antara titik data dan pusat kelompok diukur dengan menggunakan metrik jarak, seperti Euclidean atau Manhattan.
Contoh penggunaan K-Means adalah untuk pengelompokan data pelanggan, di mana kita ingin mengelompokkan pelanggan berdasarkan perilaku belanja mereka. K-Means juga dapat digunakan untuk mengurangi dimensi data, di mana kita ingin mengurangi jumlah fitur yang digunakan untuk menganalisis data.

Dalam kesimpulannya, KNN dan K-Means adalah dua algoritma machine learning yang berbeda. KNN digunakan untuk masalah klasifikasi dan regresi, sementara K-Means digunakan untuk pengelompokan dan reduksi dimensi. KNN adalah supervised learning, sementara K-Means adalah unsupervised learning.





